name: women_safety_user
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  google_maps_flutter: ^2.12.3
  location: ^8.0.1
  socket_io_client: ^3.1.2
  flutter_secure_storage: ^9.2.4
  flutter_sound: ^9.28.0
  permission_handler: ^12.0.1
  flutter_typeahead: ^5.2.0
  flutter_phone_direct_caller: ^2.2.1
  fluttertoast: ^8.2.12
  flutter_spinkit: ^5.2.1
  flutter_animate: ^4.5.2
  mime: ^2.0.0
  http: ^1.5.0-beta.2
  google_fonts: ^6.2.1
  flutter_polyline_points: ^3.0.1
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  geolocator: ^14.0.2
  record: ^6.0.0
  audioplayers: ^6.1.0
  shared_preferences: ^2.5.3
  flutter_map_cancellable_tile_provider: ^3.1.1
  uuid: ^4.5.1
  vibration: ^3.1.3
  open_route_service: ^1.2.7
  font_awesome_flutter: ^10.9.0
  share_plus: ^11.1.0
  url_launcher: ^6.3.2
  clipboard: ^2.0.2
  dio: ^5.7.0
  http_parser: ^4.1.1
  path: ^1.9.1
  path_provider: ^2.1.4
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0

# 👇 must be aligned with dependencies/dev_dependencies
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
